#ifndef HARDWARE_CONFIG_H
#define HARDWARE_CONFIG_H

#define I2C_SDA_PIN 4
#define I2C_SCL_PIN 5
#define I2C_FREQ_HZ 400000

#define DISPLAY_WIDTH 128
#define DISPLAY_HEIGHT 64
#define DISPLAY_I2C_ADDR 0x3C

#endif